POST http://localhost:8080/radar/store/single
Content-Type: application/json

{
  "id": 26,
  "name": "MissSpeedy",
  "valueOne": 10,
  "valueTwo": 20,
  "valueThree": 30,
  "valueFour": 40,
  "valueFive": 50
}

###

POST http://localhost:8080/api/horses/send
Content-Type: application/json

{
 "name": "SpeedyVonPedro"
}

###

DELETE http://localhost:8080/api/horses/delete?horseId=31

###



###
POST http://localhost:8080/track/createTrack
Content-Type: application/json

{
  "date": "2024-11-20",
  "nameOfTrack": "Romme"
}
###

###
POST http://localhost:8080/competition/createCompetition
Content-Type: application/json

{
  "nameOfCompetition": "My Competition"
}
###

###
POST http://localhost:8080/lap/createLap
Content-Type: application/json

{
  "nameOfLap": "Knuthöjden",
  "competition": {
    "id": 1
  }
}
###

###
POST http://localhost:8080/completeHorse/createCompleteHorse
Content-Type: application/json

{
  "nameOfCompleteHorse": "Champion Horse",
  "lap": {
    "id": 1
  },
  "fourStarts": {
    "id": 101
  }
}

###

###
POST http://localhost:8080/fourStarts/createFourStarts
Content-Type: application/json

{
  "analys": 90,
  "fart": 85,
  "styrka": 70,
  "klass": 80,
  "prispengar": 120000,
  "kusk": 95,
  "spar": 4
}
###

###
POST http://localhost:8080/travanalys/sendEverything
Content-Type: application/json

{
  "nameOfTrack": "ok",
  "date": "2024-11-21",
  "competitions": [
    {
      "nameOfCompetition": "v75",
      "laps": [
        {
          "nameOfLap": "Lap 1",
          "horses": [
            {
              "nameOfCompleteHorse": "Apa",
              "fourStarts": {
                "analys": 90,
                "fart": 85,
                "styrka": 70,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 95,
                "spar": 4
              }
            },
            {
              "nameOfCompleteHorse": "bbbb",
              "fourStarts": {
                "analys": 11,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            },
            {
              "nameOfCompleteHorse": "aaa",
              "fourStarts": {
                "analys": 55,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            },
            {
              "nameOfCompleteHorse": "peppe",
              "fourStarts": {
                "analys": 55,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            },
            {
              "nameOfCompleteHorse": "awd123",
              "fourStarts": {
                "analys": 55,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            }
          ]
        },
        {
          "nameOfLap": "Lap 2",
          "horses": [
            {
              "nameOfCompleteHorse": "Lill-sången",
              "fourStarts": {
                "analys": 44,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            },
            {
              "nameOfCompleteHorse": "aw3",
              "fourStarts": {
                "analys": 44,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            },
            {
              "nameOfCompleteHorse": "123awd",
              "fourStarts": {
                "analys": 33,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            },
            {
              "nameOfCompleteHorse": "awd",
              "fourStarts": {
                "analys": 11,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            },
            {
              "nameOfCompleteHorse": "Kekko",
              "fourStarts": {
                "analys": 22,
                "fart": 85,
                "styrka": 33,
                "klass": 55,
                "prispengar": 120000,
                "kusk": 55,
                "spar": 4
              }
            }
          ]
        }
      ]
    }
  ]
}

###

POST http://localhost:8080/reduced/system
Content-Type: application/json

{
  "rd": "This is the pink beaver from soviet"
}

###

###

GET http://localhost:8080/s1?id=1
Content-Type: application/json


###
DELETE http://localhost:8080/travanalys/deleteTrackByName?nameOfTrack=Pedro
###

###

#1 Create Track
POST http://localhost:8080/track/createTrack
Content-Type: application/json

{
  "date": "2024-11-16",
  "nameOfTrack": "Knuthöjden"
}
###
# Assume this Track gets auto-assigned ID 1
###

#2 Create Competition
POST http://localhost:8080/competition/createCompetition
Content-Type: application/json

{
  "nameOfCompetition": "v69",
  "track": {
    "id": 1
  }
}
###
# Assume this Competition gets auto-assigned ID 1
###

#3 Create Lap and Link to Competition
POST http://localhost:8080/lap/createLap
Content-Type: application/json

{
  "nameOfLap": "Lap 1",
  "competition": {
    "id": 1
  }
}
###
# Assume this Lap gets auto-assigned ID 1
###

#4 Create FourStarts
POST http://localhost:8080/fourStarts/createFourStarts
Content-Type: application/json

{
  "analys": 90,
  "fart": 85,
  "styrka": 70,
  "klass": 80,
  "prispengar": 120000,
  "kusk": 95,
  "spar": 4
}
###
# Assume this FourStarts gets auto-assigned ID 101
###

#5 Create CompleteHorse and Link to Lap and FourStarts
POST http://localhost:8080/completeHorse/createCompleteHorse
Content-Type: application/json

{
  "nameOfCompleteHorse": "SuperPisseawd",
  "lap": {
    "id": 1
  },
  "fourStarts": {
    "id": 8
  }
}
###





