

#1 Create Track
POST https://travanalyserver-latest.onrender.com/track/createTrack
Content-Type: application/json

{
  "date": "2024-11-10",
  "nameOfTrack": "Knuthöjden"
}
###
# Assume this Track gets auto-assigned ID 1
###

#2 Create Competition
POST https://travanalyserver-latest.onrender.com/competition/createCompetition
Content-Type: application/json

{
  "nameOfCompetition": "v75",
  "track": {
    "id": 1
  }
}
###
# Assume this Competition gets auto-assigned ID 1
###

#3 Create Lap and Link to Competition
POST https://travanalyserver-latest.onrender.com/lap/createLap
Content-Type: application/json

{
  "nameOfLap": "Lap 2",
  "competition": {
    "id": 1
  }
}
###
# Assume this Lap gets auto-assigned ID 1
###

#4 Create FourStarts
POST https://travanalyserver-latest.onrender.com/fourStarts/createFourStarts
Content-Type: application/json

{
  "analys": 30
}
###
# Assume this FourStarts gets auto-assigned ID 101
###

#5 Create CompleteHorse and Link to Lap and FourStarts
POST https://travanalyserver-latest.onrender.com/completeHorse/createCompleteHorse
Content-Type: application/json

{
  "nameOfCompleteHorse": "RiRi",
  "lap": {
    "id": 1
  },
  "fourStarts": {
    "id": 13
  }
}
###

###
POST https://travanalyserver-latest.onrender.com/travanalys/sendEverything
Content-Type: application/json

{
  "nameOfTrack": "Hagförs",
  "date": "2024-11-16",
  "competitions": [
    {
      "nameOfCompetition": "v69",
      "laps": [
        {
          "nameOfLap": "Lap 1",
          "horses": [
            {
              "nameOfCompleteHorse": "RiRi",
              "fourStarts": {
                "analys": 90,
                "fart": 85,
                "styrka": 30,
                "klass": 80,
                "prispengar": 22,
                "kusk": 95,
                "spår": 4
              }
            },
            {
              "nameOfCompleteHorse": "bbbb",
              "fourStarts": {
                "analys": 14,
                "fart": 82,
                "styrka": 33,
                "klass": 8,
                "prispengar": 12,
                "kusk": 55,
                "spår": 4
              }
            },
            {
              "nameOfCompleteHorse": "aaa",
              "fourStarts": {
                "analys": 55,
                "fart": 85,
                "styrka": 33,
                "klass": 30,
                "prispengar": 44,
                "kusk": 55,
                "spår": 4
              }
            },
            {
              "nameOfCompleteHorse": "peppe",
              "fourStarts": {
                "analys": 5,
                "fart": 8,
                "styrka": 33,
                "klass": 8,
                "prispengar": 66,
                "kusk": 55,
                "spår": 4
              }
            },
            {
              "nameOfCompleteHorse": "awd123",
              "fourStarts": {
                "analys": 55,
                "fart": 25,
                "styrka": 43,
                "klass": 80,
                "prispengar": 3,
                "kusk": 55,
                "spår": 4
              }
            }
          ]
        },
        {
          "nameOfLap": "Lap 2",
          "horses": [
            {
              "nameOfCompleteHorse": "Kekk123o",
              "fourStarts": {
                "analys": 14,
                "fart": 25,
                "styrka": 33,
                "klass": 80,
                "prispengar": 2,
                "kusk": 55,
                "spår": 4
              }
            },
            {
              "nameOfCompleteHorse": "aw3",
              "fourStarts": {
                "analys": 44,
                "fart": 85,
                "styrka": 33,
                "klass": 40,
                "prispengar": 1,
                "kusk": 25,
                "spår": 4
              }
            },
            {
              "nameOfCompleteHorse": "123awd",
              "fourStarts": {
                "analys": 33,
                "fart": 15,
                "styrka": 33,
                "klass": 30,
                "prispengar": 14,
                "kusk": 55,
                "spår": 4
              }
            },
            {
              "nameOfCompleteHorse": "awd",
              "fourStarts": {
                "analys": 11,
                "fart": 85,
                "styrka": 33,
                "klass": 80,
                "prispengar": 12,
                "kusk": 55,
                "spår": 4
              }
            },
            {
              "nameOfCompleteHorse": "Kekko",
              "fourStarts": {
                "analys": 22,
                "fart": 35,
                "styrka": 33,
                "klass": 55,
                "prispengar": 15,
                "kusk": 55,
                "spår": 4
              }
            }
          ]
        }
      ]
    }
  ]
}
###


