name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v4
        name: Check out code

      # Step 2: Grant executable permission for Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Step 3: Set up JDK 20
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: gradle  # Enables Gradle cache to speed up builds

      # Step 4: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

